In [7]:
import pandas as pd
# Veri setini yükleme
data_path = r'C:\Users\Gizem\Desktop\Veri_Seti_ChatGPT_İnsan.xlsx'
data = pd.read_excel(data_path)
# Veri setinin ilk beş satırını göster
print(data.head())
# Veri setinin sütun başlıklarını ve veri türlerini göster
print(data.info())

                                           Veri Seti       Unnamed: 1  \
0                                      Gereksinimler  Gereksinim Tipi   
1  Kullanıcıların profil bilgilerini güncelleyebi...      Fonksiyonel   
2  Profil oluşturma sırasında, evcil hayvanın tem...      Fonksiyonel   
3  Kullanıcılar, evcil hayvanlarının sağlık geçmi...      Fonksiyonel   
4  Randevu talepleri, platform üzerinden veterine...      Fonksiyonel   

  Unnamed: 2  
0      Yazar  
1    ChatGPT  
2    ChatGPT  
3    ChatGPT  
4    ChatGPT  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Veri Seti   41 non-null     object
 1   Unnamed: 1  41 non-null     object
 2   Unnamed: 2  41 non-null     object
dtypes: object(3)
memory usage: 1.1+ KB
None


In [31]:
import pandas as pd

# Veri setini yükleme
data_path = r'C:\Users\Gizem\Desktop\Veri_Seti_ChatGPT_İnsan.xlsx'
data = pd.read_excel(data_path)

# Veri setinin sütun başlıklarını ve veri türlerini göster
print(data.columns)


Index(['Gereksinimler', 'Gereksinim Tipi', 'Yazar'], dtype='object')


In [12]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# NLTK kütüphanesinin durak kelimeler ve WordNet lemmatizer'ını indir
nltk.download('stopwords')
nltk.download('wordnet')

# Veri setini yükleme
data_path = r'C:\Users\Gizem\Desktop\Veri_Seti_ChatGPT_İnsan.xlsx'
data = pd.read_excel(data_path)

# Durak kelimeler listesi
stop_words = set(stopwords.words('english'))

# Lemmatizer nesnesi
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    # Küçük harfe çevirme
    text = text.lower()
    # Noktalama işaretlerini ve sayıları kaldır
    text = re.sub(r'[\d\W]+', ' ', text)
    # Tokenize etme ve durak kelimeleri kaldırma
    words = text.split()
    words = [word for word in words if word not in stop_words]
    # Kelimeleri kökten ayırma
    words = [lemmatizer.lemmatize(word) for word in words]
    # Temizlenmiş metni geri döndür
    return ' '.join(words)

# Metin sütununu önişle
data['Processed_Text'] = data['Veri Seti'].apply(preprocess_text)

# İlk beş işlenmiş metni göster
print(data['Processed_Text'].head())

from sklearn.model_selection import train_test_split, KFold

# Önişleme adımı (metin önişlemeyi önceki adımda belirtilen gibi varsayıyorum)
data['Processed_Text'] = data['Veri Seti'].apply(preprocess_text) # Metin sütununun adını düzeltin

# Hedef sütun (ikinci sütun varsayılarak)
target = data.iloc[:, 1] # İkinci sütunu hedef olarak kullan

# Bağımsız değişkenler (özellikler)
features = data['Processed_Text']

# Veri setini eğitim ve test kümelerine ayırma
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# 10-katlı çapraz doğrulama için KFold nesnesi oluşturma
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# KFold ile çapraz doğrulama indexlerini yazdırma
for train_index, test_index in kf.split(X_train):
    print("TRAIN:", train_index, "TEST:", test_index)

# Eğitim ve test kümelerinin boyutlarını yazdır
print(f"Eğitim kümesi boyutu: {X_train.shape[0]}, Test kümesi boyutu: {X_test.shape[0]}")


0                                        gereksinimler
1    kullanıcıların profil bilgilerini güncelleyebi...
2    profil oluşturma sırasında evcil hayvanın teme...
3    kullanıcılar evcil hayvanlarının sağlık geçmiş...
4    randevu talepleri platform üzerinden veteriner...
Name: Processed_Text, dtype: object
TRAIN: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 16 18 19 20 21 22 23 25 26
 27 28 30 31] TEST: [15 17 24 29]
TRAIN: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 26
 27 28 29 31] TEST: [ 8  9 25 30]
TRAIN: [ 1  2  3  5  6  7  8  9 10 11 13 14 15 16 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31] TEST: [ 0  4 12]
TRAIN: [ 0  1  2  3  4  6  7  8  9 10 11 12 14 15 17 18 19 20 21 22 23 24 25 26
 27 28 29 30 31] TEST: [ 5 13 16]
TRAIN: [ 0  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18 19 20 21 22 24 25 26
 27 28 29 30 31] TEST: [ 1 11 23]
TRAIN: [ 0  1  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 27 28 29 30 31] TEST: [ 2  3 26]
TRAIN

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Gizem\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Gizem\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

# Veri setini yükleme
data_path = r'C:\Users\Gizem\Desktop\Veri_Seti_ChatGPT_İnsan.xlsx'
data = pd.read_excel(data_path)

# Veri setinin ilk beş satırını göster
print(data.head())

# Veri setinin sütun başlıklarını ve veri türlerini göster
print(data.info())

# Bağımlı ve bağımsız değişkenleri ayırma
X = data['Gereksinimler']  # Bağımsız değişken
y = data['Yazar']  # Bağımlı değişken

# 'Gereksinim Tipi' sütununu da X'e ekleme
X = data['Gereksinimler'] + ' ' + data['Gereksinim Tipi']

# Metin verisini sayısal hale getirme (TF-IDF)
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(X)

# 'Yazar' sütununu sayısal değerlere dönüştürme
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Eğitim ve test veri setlerini ayırma
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y_encoded, test_size=0.2, random_state=42)

# SVM modelini tanımlama ve eğitme
svm_model = SVC()
svm_model.fit(X_train, y_train)

# Modelin performansını değerlendirme
y_pred = svm_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Modelin doğruluk değeri:", accuracy)


                                       Gereksinimler Gereksinim Tipi    Yazar
0  Kullanıcıların profil bilgilerini güncelleyebi...     Fonksiyonel  ChatGPT
1  Profil oluşturma sırasında, evcil hayvanın tem...     Fonksiyonel  ChatGPT
2  Kullanıcılar, evcil hayvanlarının sağlık geçmi...     Fonksiyonel  ChatGPT
3  Randevu talepleri, platform üzerinden veterine...     Fonksiyonel  ChatGPT
4  Veri güvenliği önlemleri, platformun güvenliği...     Fonksiyonel  ChatGPT
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gereksinimler    40 non-null     object
 1   Gereksinim Tipi  40 non-null     object
 2   Yazar            40 non-null     object
dtypes: object(3)
memory usage: 1.1+ KB
None
Modelin doğruluk değeri: 0.375


In [32]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from gensim.models import Word2Vec, Doc2Vec
from gensim.models.doc2vec import TaggedDocument
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import numpy as np

# NLTK kütüphanesinin durak kelimeler ve WordNet lemmatizer'ını indir
nltk.download('stopwords')
nltk.download('wordnet')

# Veri setini yükleme
data_path = r'C:\Users\Gizem\Desktop\Veri_Seti_ChatGPT_İnsan.xlsx'
data = pd.read_excel(data_path)

# Veri setinin ilk beş satırını göster
print(data.head())

# Veri setinin sütun başlıklarını ve veri türlerini göster
print(data.info())

# Durak kelimeler listesi
stop_words = set(stopwords.words('english'))

# Lemmatizer nesnesi
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    # Küçük harfe çevirme
    text = text.lower()
    # Noktalama işaretlerini ve sayıları kaldır
    text = re.sub(r'[\d\W]+', ' ', text)
    # Tokenize etme ve durak kelimeleri kaldırma
    words = text.split()
    words = [word for word in words if word not in stop_words]
    # Kelimeleri kökten ayırma
    words = [lemmatizer.lemmatize(word) for word in words]
    # Temizlenmiş metni geri döndür
    return ' '.join(words)

# Metin sütununu önişle
data['Processed_Text'] = data['Gereksinimler'].apply(preprocess_text)

# Bağımlı ve bağımsız değişkenleri ayırma
X = data['Gereksinim Tipi']
y = data['Yazar']

# TF-IDF öznitelik çıkarımı
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(X)

# Count Vectorizer öznitelik çıkarımı
count_vectorizer = CountVectorizer()
X_count = count_vectorizer.fit_transform(X)

# Word2Vec öznitelik çıkarımı
sentences = [text.split() for text in X]
word2vec_model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)
word2vec_vectors = np.array([np.mean([word2vec_model.wv[word] for word in words if word in word2vec_model.wv] or [np.zeros(100)], axis=0) for words in sentences])

# Doc2Vec öznitelik çıkarımı
documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(sentences)]
doc2vec_model = Doc2Vec(documents, vector_size=100, window=5, min_count=1, epochs=20)
doc2vec_vectors = np.array([doc2vec_model.dv[i] for i in range(len(documents))])

# One-Hot Encoding
onehot_vectorizer = CountVectorizer(binary=True)
X_onehot = onehot_vectorizer.fit_transform(X)

# 'Yazar' sütununu sayısal değerlere dönüştürme
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Öznitelik setlerini bir sözlükte toplama
feature_sets = {
    "TF-IDF": X_tfidf,
    "CountVector": X_count,
    "Word2Vec": word2vec_vectors,
    "Doc2Vec": doc2vec_vectors,
    "One-Hot": X_onehot
}

# Modelleri tanımlama
models = {
    "Lojistik Regresyon": LogisticRegression(max_iter=1000),
    "Karar Ağacı": DecisionTreeClassifier(),
    "Rastgele Orman": RandomForestClassifier(),
    "SVM": SVC(),
    "KNN": KNeighborsClassifier()
}

# Her öznitelik seti ve model için eğitim, test ve performans değerlendirmesi yapma
results = {}
for feature_name, features in feature_sets.items():
    X_train, X_test, y_train, y_test = train_test_split(features, y_encoded, test_size=0.2, random_state=42)
    results[feature_name] = {}
    for model_name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        report = classification_report(y_test, y_pred, output_dict=True)
        cm = confusion_matrix(y_test, y_pred)
        results[feature_name][model_name] = {
            "Precision": report['weighted avg']['precision'],
            "Recall": report['weighted avg']['recall'],
            "F1-Score": report['weighted avg']['f1-score'],
            "Confusion Matrix": cm
        }
        print(f"{feature_name} - {model_name} ile Performans:")
        print(f"Precision: {report['weighted avg']['precision']:.2f}")
        print(f"Recall: {report['weighted avg']['recall']:.2f}")
        print(f"F1-Score: {report['weighted avg']['f1-score']:.2f}")
        print(f"Confusion Matrix:\n{cm}\n")

# Sonuçları topluca yazdırma (isteğe bağlı)
print("Tüm Sonuçlar:")
print(results)


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Gizem\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Gizem\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


                                       Gereksinimler Gereksinim Tipi    Yazar
0  Kullanıcıların profil bilgilerini güncelleyebi...     Fonksiyonel  ChatGPT
1  Profil oluşturma sırasında, evcil hayvanın tem...     Fonksiyonel  ChatGPT
2  Kullanıcılar, evcil hayvanlarının sağlık geçmi...     Fonksiyonel  ChatGPT
3  Randevu talepleri, platform üzerinden veterine...     Fonksiyonel  ChatGPT
4  Veri güvenliği önlemleri, platformun güvenliği...     Fonksiyonel  ChatGPT
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gereksinimler    40 non-null     object
 1   Gereksinim Tipi  40 non-null     object
 2   Yazar            40 non-null     object
dtypes: object(3)
memory usage: 1.1+ KB
None
TF-IDF - Lojistik Regresyon ile Performans:
Precision: 0.28
Recall: 0.25
F1-Score: 0.25
Confusion Matrix:
[[1 4]
 [2 1]]

TF-IDF - Karar Ağacı ile Performans:
P

C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metr

Word2Vec - Karar Ağacı ile Performans:
Precision: 0.28
Recall: 0.25
F1-Score: 0.25
Confusion Matrix:
[[1 4]
 [2 1]]

Word2Vec - Rastgele Orman ile Performans:
Precision: 0.28
Recall: 0.25
F1-Score: 0.25
Confusion Matrix:
[[1 4]
 [2 1]]

Word2Vec - SVM ile Performans:
Precision: 0.14
Recall: 0.38
F1-Score: 0.20
Confusion Matrix:
[[0 5]
 [0 3]]



C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Word2Vec - KNN ile Performans:
Precision: 0.28
Recall: 0.25
F1-Score: 0.25
Confusion Matrix:
[[1 4]
 [2 1]]

Doc2Vec - Lojistik Regresyon ile Performans:
Precision: 0.14
Recall: 0.38
F1-Score: 0.20
Confusion Matrix:
[[0 5]
 [0 3]]

Doc2Vec - Karar Ağacı ile Performans:
Precision: 0.57
Recall: 0.50
F1-Score: 0.50
Confusion Matrix:
[[2 3]
 [1 2]]



C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Doc2Vec - Rastgele Orman ile Performans:
Precision: 0.79
Recall: 0.50
F1-Score: 0.43
Confusion Matrix:
[[1 4]
 [0 3]]

Doc2Vec - SVM ile Performans:
Precision: 0.14
Recall: 0.38
F1-Score: 0.20
Confusion Matrix:
[[0 5]
 [0 3]]



C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Doc2Vec - KNN ile Performans:
Precision: 0.85
Recall: 0.75
F1-Score: 0.75
Confusion Matrix:
[[3 2]
 [0 3]]

One-Hot - Lojistik Regresyon ile Performans:
Precision: 0.28
Recall: 0.25
F1-Score: 0.25
Confusion Matrix:
[[1 4]
 [2 1]]

One-Hot - Karar Ağacı ile Performans:
Precision: 0.28
Recall: 0.25
F1-Score: 0.25
Confusion Matrix:
[[1 4]
 [2 1]]

One-Hot - Rastgele Orman ile Performans:
Precision: 0.28
Recall: 0.25
F1-Score: 0.25
Confusion Matrix:
[[1 4]
 [2 1]]

One-Hot - SVM ile Performans:
Precision: 0.28
Recall: 0.25
F1-Score: 0.25
Confusion Matrix:
[[1 4]
 [2 1]]

One-Hot - KNN ile Performans:
Precision: 0.14
Recall: 0.38
F1-Score: 0.20
Confusion Matrix:
[[0 5]
 [0 3]]

Tüm Sonuçlar:
{'TF-IDF': {'Lojistik Regresyon': {'Precision': 0.2833333333333333, 'Recall': 0.25, 'F1-Score': 0.25, 'Confusion Matrix': array([[1, 4],
       [2, 1]], dtype=int64)}, 'Karar Ağacı': {'Precision': 0.2833333333333333, 'Recall': 0.25, 'F1-Score': 0.25, 'Confusion Matrix': array([[1, 4],
       [2, 1]], dt

C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Gizem\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
